# all amazon categories
dataset_names = [
    "Appliances",
    "Automotive",
    "Electronics",
    "Office_Products",
    "Tools_and_Home_Improvement",
    "Cell_Phones_and_Accessories",
    "Toys_and_Games",
    "Musical_Instruments",
    # "All_Beauty",
    # "Amazon_Fashion",
    # "Arts_Crafts_and_Sewing",
    # "Baby_Products",
    # "Beauty_and_Personal_Care",
    # "Books",
    # "CDs_and_Vinyl",
    # "Clothing_Shoes_and_Jewelry",
    # "Digital_Music",
    # "Gift_Cards",
    # "Grocery_and_Gourmet_Food",
    # "Handmade_Products",
    # "Health_and_Household",
    # "Health_and_Personal_Care",
    # "Home_and_Kitchen",
    # "Industrial_and_Scientific",
    # "Kindle_Store",
    # "Magazine_Subscriptions",
    # "Movies_and_TV",
    # "Patio_Lawn_and_Garden",
    # "Pet_Supplies",
    # "Software",
    # "Sports_and_Outdoors",
    # "Subscription_Boxes",
    # "Unknown",
    # "Video_Games",
]
